### ISSUE TITLE
EXIF fields with non-Roman characters

### ISSUE THREAD

**Issue by ehcloninger** [mceachen/exiftool#4]
I have some images with utf-8 encoded descriptions and captions. These seem to throw an exception in the gem as part of a Jekyll build. I can rescue from the exception and generate empty output utf-8 should work.

I'll attach a sample, but this is the offending line...
Description                     : Guarulhos airport, Saó Paulo, Brazil

Macbook Pro running Yosemite.
Jekyll 2.5.3 which is utf-8 by default.

![imgp6692](https://cloud.githubusercontent.com/assets/398033/10719038/1a963096-7b4e-11e5-9ba1-7e364570fb2a.jpg)

**Comment by mceachen** [comment]
Thanks for the report and sample image. I'll take a look.

**Comment by ehcloninger** [comment]
Lightroom reverse geocoded photos from France and Belgium with EXIF values like City=Fère-en-Tardenois, State=Île-de-France, Province-State=Région-wallonne, etc. I don't use these values, but them being in the metadata threw an exception. Thanks for looking.

**Comment by morozgrafix** [comment]
I just attempted to reproduce this and seems like utf-8 descriptions are handled correctly with exiftool 10.25 I will try to add tests to validate those cases.

**Comment by morozgrafix** [comment]
@ehcloninger I know I'm 10 months late on this. What OS are you using. I just tried to reproduce it on OS X and Linux and utf-8 seems to be working.

**Comment by mceachen** [comment]
@morozgrafix thanks for the test, I can't repro either. I'm assuming charset issues were resolved thanks to ruby 2.x

**Comment by ehcloninger** [comment]
Thanks for testing and confirming the fix. I don't have the environment to confirm the problem exists still, so agree it should be closed.
