### ISSUE TITLE
Mutliget returns nil

### ISSUE THREAD

**Issue by nielssorensen** [mceachen/exiftool#5]
I can try to pass an array of files as:
```pics = Exiftool.new(Dir["/Users/niels/Pictures/Photos\ Library.photoslibrary/**/*.jpg"])```
However, 'pics' will be nil.

An array of the files with full path can be created with just
```e = Dir["/Users/niels/Pictures/Photos\ Library.photoslibrary/**/*.jpg"]```
```f = Exiftool.new(e)``` will also cause f to be nil.
There are just over 20,000 files in the array "e".

I don't know what the issue is.  Is it perl, the exiftool perl program?  Is it ruby? The gem?  Please let me know what I can do to help.

**Comment by mceachen** [comment]
Does it fail even if there are only, say, 10 items? Try `e.first(10)`.

**Comment by nielssorensen** [comment]
With 10 items:
```f = Exiftool.new(e.first(10))```
```output error: #<Exiftool::NoDefaultResultWithMultiget: use #result_for when multiple filenames are used>```

**Comment by nielssorensen** [comment]
```
Errno::E2BIG: Argument list too long - exiftool  -j -coordFormat "%.8f"
...snip...
.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/exiftool-0.7.0/lib/exiftool.rb:49:in ``'
```

**Comment by mceachen** [comment]
Sorry, I didn't see the part that you were asking for 20,000 files at once. 

Exiftool is pretty fast, but that's still many, many hours of processing. You should page through that many files.

The error returned, "Argument list too long," is a reasonable error to throw in this case. I'm closing this as this is correct behavior.
