### ISSUE TITLE
using the '-n' option for an image with gps coordinates gives warnings

### ISSUE THREAD

**Issue by rempargo** [mceachen/exiftool#7]
I'm running the following command with the extra argument `-n` to extract the real exif data (I want the integer value for the orientation tag).

`Exiftool.new('some-image-file.jpg,'-n').to_hash`

I see some warnings for both the 'GPSLatitude' & 'GPSLongitude':
`:gps_latitude=>"Warning: Parsing '52.7353472222222' for attribute 'GPSLatitude' raised undefined method `split' for 52.7353472222222:Float"`

added an image for any testing:
![2016-08-30 11 06 47](https://cloud.githubusercontent.com/assets/261394/18083140/21d86b1a-6ea2-11e6-8f52-d66738e5695f.jpg)

**Comment by mceachen** [comment]
Thanks for opening the issue, @rempargo and the PR @morozgrafix ! 👍
